export const VISIBILITIES = {
  HIDDEN: 0,
  SET: 1,
  HOVER: 2,
  FIXED: 3,
};

export const CONVERSATION_VIEW_MODES = {
  VIEW: "VIEW",
  NEW: "NEW",
};
export const CHAT_VIEW_MODES = {
  VIEW: "VIEW",
  ADD_PARTICIPANTS: "ADD_PARTICIPANTS",
  INFO: "INFO",
  WHISPER: "WHISPER",
  MESSAGE: "MESSAGE",
};
